### ISSUE TITLE
How can I get the YBB image dateset that is used to train Dummy_Gan?

### ISSUE THREAD

**Issue by MarcellusZhao** [vobecant/DummyNet#1]
In this repo, I cannot find the image files that is under the path ('/home/vobecant/datasets/YBB/GAN_data/images' and '/home/vobecant/datasets/YBB/GAN_data/masks') in your project. The access to these images will help me a lot! Thx!

**Comment by dhurych** [comment]
Hi MarcellusZhao. The Youtube Bounding Boxes dataset is shared just as a list of videos to download [here](https://research.google.com/youtube-bb/download.html).  The license of this dataset does not allow to share the videos/images directly. But you may use these [codes ](https://github.com/mbuckler/youtube-bb) to download the available videos. It may happen that some of the videos will no longer be available because some users may have deleted them. We did not use the original YoutubeBB annotation. We have used the [OpenPose ](https://github.com/CMU-Perceptual-Computing-Lab/openpose) to pass through videos from class "person" and "skateboard" and extracted samples from it.

**Comment by minorli96** [comment]
老哥，为啥我run augment_nightowls.py ./data/weights ./result ./data/YBB/nightowls_bbs test is  ./data/YBB/nightowls_bbs 这个语句就报错了，报错信息是：
Traceback (most recent call last):
  File "/root/lvyisheng_1_1/Lb/augment_nightowls.py", line 167, in <module>
    scene = to_tensor(Image.open(image_path).convert('RGB'))
  File "/root/anaconda3/envs/python_lb/lib/python3.6/site-packages/PIL/Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/vobecant/datasets/nightowls/nightowls_training/58c58133bc260137e096a58a.png'

是需要更改默认参数吗？
万分感谢老哥解答！

**Comment by vobecant** [comment]
Dear @lulubbb ,

if you have dowloaded the nightowls dataset, then I guess that you can fix this simply by replacing line [118](https://github.com/vobecant/DummyNet/blob/678859d1bc1c322c04f9079f533d254fb6e20ec1/augment_nightowls.py#L118) by 

```
ORIG_PATH = '/home/vobecant/datasets/nightowls/nightowls_training'
YOUR_PATH_TO_NIGHTOWLS_TRAIN = None # fill your path to the nightowls training images
background_paths = [sample['filepath'] for sample in bboxes_orig]
background_paths = [p.replace(ORIG_PATH, YOUR_PATH_TO_NIGHTOWLS_TRAIN) for p in background_paths]
```

**Comment by minorli96** [comment]
Dear @vobecant ,
thanks for your replay! after your remind, i try to download the nightowls dataset, but [download page](https://thor.robots.ox.ac.uk/~vgg/data/nightowls/python/nightowls_training.zip)have faild to open, so  is this the correct way to download？ thanks again for your great reserach work!

**Comment by MarcellusZhao** [comment]
需要修改文件路径参数。
________________________________
发件人: luBo ***@***.***>
发送时间: 2021年11月1日 7:56
收件人: vobecant/DummyNet ***@***.***>
抄送: MarcellusZhao ***@***.***>; Author ***@***.***>
主题: Re: [vobecant/DummyNet] How can I get the YBB image dateset that is used to train Dummy_Gan? (#1)


老哥，为啥我run augment_nightowls.py ./data/weights ./result ./data/YBB/nightowls_bbs test is ./data/YBB/nightowls_bbs 这个语句就报错了，报错信息是：
Traceback (most recent call last):
File "/root/lvyisheng_1_1/Lb/augment_nightowls.py", line 167, in
scene = to_tensor(Image.open(image_path).convert('RGB'))
File "/root/anaconda3/envs/python_lb/lib/python3.6/site-packages/PIL/Image.py", line 2891, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/vobecant/datasets/nightowls/nightowls_training/58c58133bc260137e096a58a.png'

是需要更改默认参数吗？
万分感谢老哥解答！

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvobecant%2FDummyNet%2Fissues%2F1%23issuecomment-956303622&data=04%7C01%7C%7C047d1ca3da1d4bc7d97808d99d47c014%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637713753761047162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BHFG35xXXmtT7%2FmnlmkmbPCYalvGH9VkrRTFeucA9D8%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMCPQTAC56TJFMH2J7ADYK3UJ2TA3ANCNFSM46AGNXIQ&data=04%7C01%7C%7C047d1ca3da1d4bc7d97808d99d47c014%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637713753761047162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MGW9Qie8D8bpxqZegcCOdMC9YAQHA6HN7EJV0DjbB70%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C047d1ca3da1d4bc7d97808d99d47c014%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637713753761057119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IQLJWOIVgsn4evkOs3Gtp9Sx7LD0GrHxFI0PI0pApwY%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C047d1ca3da1d4bc7d97808d99d47c014%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637713753761057119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oaAb1Cz2YoLIlgvTB96mF6ctZ403rcK9%2FbR%2FnGOmT7w%3D&reserved=0>.

**Comment by minorli96** [comment]
请问老哥，你是怎么下到nightowls这个数据集的，我找一个圈也没找到，官方给出的链接也进不去（不是梯子的问题）

**Comment by MarcellusZhao** [comment]
你好，我点开你的链接就自动开始下了，我人在国外，可能是梯子的问题？

希望能帮到你
________________________________
发件人: luBo ***@***.***>
发送时间: 2021年11月2日 1:52
收件人: vobecant/DummyNet ***@***.***>
抄送: MarcellusZhao ***@***.***>; Author ***@***.***>
主题: Re: [vobecant/DummyNet] How can I get the YBB image dateset that is used to train Dummy_Gan? (#1)


请问老哥，你是怎么下到nightowls这个数据集的，我找一个圈也没找到，官方给出的链接也进不去（不是梯子的问题）

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvobecant%2FDummyNet%2Fissues%2F1%23issuecomment-957232557&data=04%7C01%7C%7Cc7b093ff7b80467019a808d99dde21da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637714399644202895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K960rKwaUNso3EMMEeFZRuocgqsUqBsD9APMlFdeMX8%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMCPQTAC5OY5KO4TD2WF3ILUJ6RFTANCNFSM46AGNXIQ&data=04%7C01%7C%7Cc7b093ff7b80467019a808d99dde21da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637714399644212826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qAEw%2B2rvfzUW%2BLwLk17pW6Mys78vKwcRIERCSmoerHI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc7b093ff7b80467019a808d99dde21da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637714399644212826%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zQVDn8rkRx2JY%2BDGPW%2FP6msqLwaL0DS3U18J0JbrRFI%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc7b093ff7b80467019a808d99dde21da%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637714399644222800%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yKA7x5Bk1eeAZXgZrieUXmh8l%2FdSk%2FKFGf%2B6MXB9tC0%3D&reserved=0>.

**Comment by minorli96** [comment]
好的，万分感谢，原来是我梯子的问题，感谢解惑！祝科研顺利~

**Comment by vobecant** [comment]
@lulubbb , the download link works fine for me

**Comment by minorli96** [comment]
@vobecant thanks, lt's a vpn mistake of my chrome setting.  i just solved this problem
